version: "3.7"

services:
    laravel-setup:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - laravel-setup-network
    # nginx
    nginx:
        container_name: laravel-setup-nginx
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel-setup-network
    mysql:
        container_name: laravel-setup-mysql
        image: mysql:8.0
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: banco
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: password
            MYSQL_USER: user
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - laravel-setup-network
            
networks:
    laravel-setup-network:
        driver: bridge

